### ISSUE TITLE
Server zuerst schreiben?

### ISSUE THREAD

**Issue by DevKame** [DevKame/timeseries_predictor#3]
@999Fritsch 
Meinst du, du kannst den Server zuerst schreiben? Denn wenn ich das Frontend zum Hochladen einer .csv Datei baue, wäre es top wenn diese denn zum Testen auch an einen Server geschickt wird.

Der Server kann für den Anfang die .csv Daten gerne so blank zurückschicken, ohne irgendeine Bearbeitung. Es geht mir nur darum dass ich als Response Daten bekomme und damit die Darstellugn dieser Daten in Angriff nehmen kann.

**Comment by 999Fritsch** [comment]
wird gemacht chef B)
